# Generated by Django 4.2.7 on 2023-12-04 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_lost', models.DateField()),
                ('location_lost', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=100)),
                ('date_reported', models.DateField(auto_now_add=True)),
                ('image', models.BinaryField(blank=True, max_length='max', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_found', models.DateField()),
                ('location_found', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=100)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('image', models.BinaryField(blank=True, max_length='max', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
