# Generated by Django 4.2.7 on 2023-12-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostitem',
            name='image',
        ),
        migrations.AlterField(
            model_name='founditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='found_item_images/'),
        ),
    ]
