# Generated by Django 4.2.7 on 2023-12-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_founditem_admin_received_alter_founditem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='owner_collected',
            field=models.BooleanField(default=False),
        ),
    ]
